local SLIME_NB = 10
local min_y = 100
local max_y = 500
local min_x = 100
local max_x = 1500

function init(self)
	math.randomseed(0)
	for i = 1, SLIME_NB do
		local x = math.random(min_x, max_x)
		local y = math.random(min_y, max_y)
		local v = vmath.vector3(x, y, 0)
		local component = "#slimegreen_factory"
		if math.random() < 0.2 then
			component = "#slimeorange_factory"
		end
		factory.create(component, v)
	end
end
